version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    environment:
      NODE_ENV: "production"
    restart: unless-stopped
    command: ["dumb-init", "pnpm", "run", "dev"]
